language: julia

os:
  - linux

julia:
  - 1.5

notifications:
  email: false

sudo: false

branches:
  only:
    - master
    - stable
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # for tagging

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MarketTechnicals"); Pkg.test("MarketTechnicals", coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.add("MarketData")'
  - julia -e 'cd(Pkg.dir("MarketTechnicals", "docs")); include("make.jl")'

  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("MarketTechnicals")); using Coverage; Codecov.submit(process_folder())'
